version: "3.9"

services:
    recognizer:
        image: recognizer:latest
        container_name: recognizer
        ports:
            - "8001:8000"
        restart: unless-stopped

    decomposer:
        image: decomposer:latest
        container_name: decomposer
        ports:
            - "8002:8000"
        restart: unless-stopped

    relation-classifier:
        image: relation-classifier:latest
        container_name: relation-classifier
        ports:
            - "8003:8000"
        restart: unless-stopped

    formalizer:
        image: formalizer:latest
        container_name: formalizer
        ports:
            - "8004:8000"
        restart: unless-stopped